### ISSUE TITLE
[Feature]: r8152 network interface does not come up with only Linux config

### ISSUE THREAD

**Issue by negge** [kendryte/k230_sdk#35] opened 2023-11-19 00:11 UTC
### Feature description

Using the [k230_evb_only_linux_defconfig](https://github.com/kendryte/k230_sdk/blob/main/configs/k230_evb_only_linux_defconfig) as a template, I created a [k230_canmv_defconfig](https://github.com/negge/k230_sdk/commit/bc4d9e84184f4d4d03d0fb3b2dd3597e105cd798) that is only Linux and uses all 512MB of memory.

However, no matter what I do I always get this error bringing up the network adapter when booting:

```
[    2.755204] usb 2-1: New USB device found, idVendor=0bda, idProduct=8152, bcdDevice=20.00
[    2.763408] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.770548] usb 2-1: Product: USB 10/100 LAN
[    2.774821] usb 2-1: Manufacturer: Realtek
[    2.778919] usb 2-1: SerialNumber: 000000000000
[    2.783665] mmc1: err:-110 ocr=0x0 
[    2.788434] r8152 2-1:1.0: Unknown version 0x08f0
```

Please add a full `k230_canmv_only_linux_defconf` that works with the Realtek USB hardware and boots up with eth0.

**Comment by negge** [comment] 2023-11-20 10:43
I was able to get it working. There is a race condition in the r8152 driver bring up. If you reboot the machine over and over eventually it works. I was on very fast storage and so it always failed.

This has been fixed in newer kernels ([among](https://github.com/torvalds/linux/commit/d9962b0d42029bcb40fe3c38bce06d1870fa4df4) [many](https://github.com/torvalds/linux/commit/61b0ad6f58e2066e054c6d4839d67974d2861a7d) [other](https://github.com/torvalds/linux/commit/8ceda6d5a1e5402fd852e6cc59a286ce3dc545ee) [bugs](https://github.com/torvalds/linux/commit/93e2be344a7db169b7119de21ac1bf253b8c6907)). Any chance of moving to a 6.6 (or later) kernel that has hwprobe()?

**Comment by xiangbingj** [comment] 2023-11-21 01:12
> I was able to get it working. There is a race condition in the r8152 driver bring up. If you reboot the machine over and over eventually it works. I was on faster storage and so it always failed.
> 
> This has been fixed in newer kernels ([among](https://github.com/torvalds/linux/commit/d9962b0d42029bcb40fe3c38bce06d1870fa4df4) [many](https://github.com/torvalds/linux/commit/61b0ad6f58e2066e054c6d4839d67974d2861a7d) [other](https://github.com/torvalds/linux/commit/8ceda6d5a1e5402fd852e6cc59a286ce3dc545ee) [bugs](https://github.com/torvalds/linux/commit/93e2be344a7db169b7119de21ac1bf253b8c6907)). Any chance of moving to a 6.6 (or later) kernel that has hwprobe()?

Thank you very much for providing the information. Considering the workload, it should not be moved to the 6.6 kernel, but we can refer to the 6.6 kernel to fix this bug.

**Comment by negge** [comment] 2023-12-06 16:38
Just as an update, other folks who have the same K230 have tried backporting kernel patches for the r8152 network driver and are still seeing issues with it coming online:

_10:36 < courmisch> well maybe someone should ping that bug to point out that the kernel fixes don't really address the problem
10:43 < courmisch> What I see is that backporting most (admittedly not all, since some of them depend on netdev API changes) seems to fix the immediate issue of "unknown version"... but the eth0 device just ends up in NO-CARRIER mode
10:44 < courmisch> TBH, I'm starting to suspect the USB controller is at fault, not the NIC_

There is likely another issue than just missing kernel fixes for the r8152 driver.

**Comment by xiangbingj** [comment] 2023-12-07 12:02
> Just as an update, other folks who have the same K230 have tried backporting kernel patches for the r8152 network driver and are still seeing issues with it coming online:
> 
> _10:36 < courmisch> well maybe someone should ping that bug to point out that the kernel fixes don't really address the problem 10:43 < courmisch> What I see is that backporting most (admittedly not all, since some of them depend on netdev API changes) seems to fix the immediate issue of "unknown version"... but the eth0 device just ends up in NO-CARRIER mode 10:44 < courmisch> TBH, I'm starting to suspect the USB controller is at fault, not the NIC_
> 
> There is likely another issue than just missing kernel fixes for the r8152 driver.
This bug is really puzzling. This bug doesn't appear every time.
Have you tested it on the canmv development board? I cannot reproduce this bug on the canmv development board.
I've only encountered this bug when using an external USB to Ethernet device. I once wondered if it was related to the USB to Ethernet hardware circuit.
I think we can solve this bug based on more experiments.

**Comment by wuwentao** [comment] 2024-07-26 03:49
please doule check with latest sdk code, this issue should be fixed. 
and we also not received any new response for a long time, so just close current issue.

if you found this issue still exist with latest code, you still can reopen current issue and continue report bug.

Thanks

**Closed by wuwentao** 2024-07-26 03:49 UTC
